# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      docs/conf\.py|
      tests/test_tocdirective/.*|
      tests/test_sphinx_jupyterbook_latex/.*|
    )$

repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  # this is not used for now,
  # since it converts jupyter-book to jupyter_book and removes comments
  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v1.17.0
  #   hooks:
  #   - id: setup-cfg-fmt

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
    - id: check-manifest
      args: [--no-build-isolation]
      additional_dependencies: [setuptools>=46.4.0]

  - repo: local
    hooks:
    - id: check-doc-req
      name: Check docs/requirements.txt up-to-date
      pass_filenames: false
      files: >-
          (?x)^(
              setup.cfg|
              docs/requirements.txt|
              scripts/check_doc_requirements.py|
          )$
      language: python
      language_version: python3
      entry: python scripts/check_doc_requirements.py

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
